### ISSUE TITLE
menu_handbook build files need update to python3

### ISSUE THREAD

**Issue by df8oe** [df8oe/mchf-github#1843]
My workstation where UHSDR builds are done now uses python3 as default. Handbook builds now stop with

Traceback (most recent call last):
  File "./ui_menu_structure_c2py.py", line 37, in <module>
    BUILD_ID = MAJ + "." + MIN + "." + REL
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "./ui_menu_structure_graph.py", line 11, in <module>
    from ui_menu_structure_c2py import MENU_DESCRIPTOR, BUILD_ID
  File "/home/andreas/git/uhsdr/mchf-eclipse/support/ui/menu/ui_menu_structure_c2py.py", line 37, in <module>
    BUILD_ID = MAJ + "." + MIN + "." + REL
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "./ui_menu_structure_mdtable.py", line 12, in <module>
    from ui_menu_structure_c2py import MENU_DESCRIPTOR, BUILD_ID
  File "/home/andreas/git/uhsdr/mchf-eclipse/support/ui/menu/ui_menu_structure_c2py.py", line 37, in <module>
    BUILD_ID = MAJ + "." + MIN + "." + REL
TypeError: can't concat str to bytes

**Comment by db4ple** [comment]
Hi,
this is a common update issue as python3 changed a couple of this in the str vs. bytes handling.
